### ISSUE TITLE
카드 등록 시 Custom UI 를 사용 할수있나요?

### ISSUE THREAD

**Issue by mwmw7** [PAYPLECORP/sample-node#4]
샘플코드를 보면 

서버쪽에서 REST call로 카드등록 가능한 것으로 보이는데요 

전화 상담 시에는 제공되는 카드등록 UI 만 사용 가능하다고 하셔서 헷갈리네요

**Comment by PAYPLECORP** [comment]
메일로 안내드렸습니다. 확인 후 회신 부탁드립니다.
